### PR TITLE
Updated if statement to switch statement

### PR DESCRIPTION
**Pull request by matthewrsj**
All logic still works. Template states below:

* Default: http://i.imgur.com/PZjiK2T.png
* CASS: http://i.imgur.com/ZIXE1K7.png
* OSL: http://i.imgur.com/Y3hPN9Q.png
* SDG: http://i.imgur.com/p2jKVuf.png
* TL: http://i.imgur.com/eWDheiH.png

### CODE REVIEW

**Comment by matthewrsj** [comment]
Fixes #2

**Comment by MaraJade** [comment]
+1

**Comment by Kennric** [comment]
Looks good - I think it might be a good idea to use the switch statement's built-in default case instead of relying on a 'default' string in the choices (what if an invoice comes in with a number not in your map, but not 1?) http://php.net/manual/en/control-structures.switch.php

**Comment by Kennric** [comment]
That's better. +1

**Pull request merged**
